mp3/mp3/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
import post.views

urlpatterns = [
    url(r'^viewItem/accept/', post.views.accept),
    url(r'^viewItem/reject/', post.views.reject),
    url(r'^cancel/', post.views.cancel),
    url(r'^messages/', post.views.messages),
    url(r'^offer/', post.views.offer),
    url(r'^viewItem/', post.views.viewItem),
    url(r'^post/', post.views.post),
    url(r'^profile/', post.views.profile),
    url(r'^logout/', post.views.logout),
    url(r'^login/', post.views.login),
    url(r'^register/', post.views.register),
    url(r'^admin/', admin.site.urls),
    url(r'^$', post.views.viewPosts),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mp3/post/models.py
from django.db import models
from . validators import valid_post_type, valid_user_type
from taggit.managers import TaggableManager

user_choices = (('student', 'Student Account'), ('professor', 'Professor Account'))
post_choices = (('academic', 'Academic Use'), ('office', 'Office Use'))

# Create your models here.
class User(models.Model):
    user_name = models.CharField(max_length=50)
    user_email = models.EmailField()
    user_password = models.CharField(max_length=16)
    user_type = models.CharField(max_length=20, choices=user_choices, default='student', validators=[valid_user_type])
    user_pic = models.ImageField(upload_to='img/user/', default='img/user/default.png')

class Post(models.Model):
    post_owner = models.ForeignKey(User, on_delete=models.CASCADE)
    post_name = models.CharField(max_length=30)
    post_description = models.TextField()
    post_price = models.PositiveIntegerField(default=0)
    post_posted = models.DateTimeField(auto_now=True)
    post_type = models.CharField(max_length=20, choices=post_choices, default='academic', validators=[valid_post_type])
    post_course = models.CharField(default="N/A", max_length=15)
    post_pic = models.ImageField(upload_to='img/posts/', default='img/posts/default.jpg')
    post_tags = TaggableManager()

class Message(models.Model):
    message = models.TextField(default="")
    mFrom = models.ForeignKey(User, on_delete=models.CASCADE, related_name="receiver", unique=False)
    mTo = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender", unique=False)
    dateSent = models.DateTimeField(auto_now=True)

class Offer(models.Model):
    offer_post = models.ForeignKey(Post, on_delete=models.CASCADE)
    offer_user = models.ForeignKey(User, on_delete=models.CASCADE)
    
class ItemOffer(models.Model):
    itemO_offer = models.ForeignKey(Offer, on_delete=models.CASCADE)
    item = models.ForeignKey(Post, on_delete=models.CASCADE)
    
class MoneyOffer(models.Model):
    moneyO_offer = models.ForeignKey(Offer, on_delete=models.CASCADE)
    money = models.PositiveIntegerField(default=0)

mp3/post/forms.py
from django import forms
from .models import User, Post, Offer, ItemOffer, MoneyOffer, Message

post_choices = (('all', 'All Types'), ('academic', 'Academic Type'), ('office', 'Office Type'))
post_limit_choices = ((10, '10'), (15, '15'), (20, '20'))

class UserLogin(forms.ModelForm):
    class Meta:
        model = User
        fields = ['user_email', 'user_password']
        
        widgets = {
            'user_email': forms.EmailInput(attrs={'required': True, 'placeholder': 'Account Email'}),
            'user_password': forms.PasswordInput(attrs={'required': True, 'placeholder': 'Account Password'}),
        }

        labels = {
            'user_email': 'Email Address',
            'user_password': 'Password',
        }

class UserRegister(forms.ModelForm):
    class Meta:
        model = User
        fields = ['user_name', 'user_type', 'user_email', 'user_password', 'user_pic']

        widgets = {
            'user_name': forms.TextInput(attrs={'required': True, 'placeholder': 'Full Name...'}),
            'user_email': forms.EmailInput(attrs={'required': True, 'placeholder': 'Account Email...'}),
            'user_password': forms.PasswordInput(attrs={'required': True, 'placeholder': 'Account Password...'}),
        }

        labels = {
            'user_name': 'Full Name',
            'user_type': 'Account Type',
            'user_pic': 'Profile Picture',
            'user_email': 'Email Address',
            'user_password': 'Password',
        }

class PostItem(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['post_name', 'post_description', 'post_price', 'post_type', 'post_course', 'post_tags', 'post_pic']
        help_texts = {
            'post_tags': '',
        }

        widgets = {
            'post_name': forms.TextInput(attrs={'required': True, 'placeholder': 'Item Name'}),
            'post_description': forms.TextInput(attrs={'required': True, 'placeholder': 'Item Description...'}),
            'post_price': forms.NumberInput(attrs={'required': True, 'placeholder': 'Item Price...'}),
            'post_tags': forms.Textarea(attrs={'required': True, 'placeholder': 'Item Tags (separated by commas)...'}),
            'post_pic': forms.ClearableFileInput(attrs={'required': False}),
            'post_course': forms.TextInput(attrs={'required': True, 'placeholder': 'Type N/A if for office use'}),
        }

        labels = {
            'post_name': 'Post Title',
            'post_description': 'Item Description',
            'post_price': 'Item Price (Php.)',
            'post_type': 'Item Type',
            'post_tags': 'Item Tags',
            'post_pic': 'Item Picture',
        }

class SearchPost(forms.ModelForm):
    post_type = forms.CharField(required=True, label="Post Type", widget=forms.Select(choices=post_choices))
    limit = forms.CharField(label="Posts Limit", widget=forms.Select(choices=post_limit_choices, attrs={'required': True}))

    post_tags = forms.CharField(required=False, label='Tag Search', widget=forms.TextInput(attrs={'required': False, 'placeholder': 'Item Tags (separated by space)...'}))
    user = forms.CharField()

    class Meta:
        model = Post
        fields = ['post_tags']

        help_texts ={
            'post_tags': '',
        }
        labels = {
            'post_tags': 'Tag Search'
        }

    def __init__(self, userId=None, *args, **kwargs):
        super(SearchPost, self).__init__(*args, **kwargs)

        if userId is None:
            del self.fields['user']
        else:
            self.fields['user'] = forms.CharField(widget=forms.HiddenInput(attrs={'value': userId}))

class OfferMoney(forms.ModelForm):
    class Meta:
        model = MoneyOffer

        fields = ['money']

        widgets = {
            'money': forms.NumberInput(attrs={'required': True})
        }

        labels = {
            'money': 'Money Offer'
        }

class OfferItem(forms.ModelForm):
    class Meta:
        model = ItemOffer

        fields = ['item']

        labels = {
            'item': 'Item Offer',
        }

    def __init__(self, user, *args, **kwargs):
        super(OfferItem, self).__init__(*args, **kwargs)
        self.fields['item'] = forms.ModelChoiceField(queryset=Post.objects.filter(post_owner_id=user), required=True)
        self.fields['item'].label_from_instance = lambda obj: "%s" % obj.post_name

class SendMessage(forms.ModelForm):
    class Meta:
        model = Message

        fields = ['message']

mp3/post/views.py
import math

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .models import Post, ItemOffer, MoneyOffer, Offer, Message
from .forms import SearchPost, UserLogin, UserRegister, User, PostItem, OfferItem, OfferMoney


# Create your views here.
def viewPosts(request, user=None, page=None):
    initial = {}
    limit = 10
    page = 1
    post = Post.objects.all()
    p = Post

    if 'page' in request.GET:
        page = request.GET['page']

    if 'limit' in request.GET:
        if  request.GET['limit'] is 15:
            limit = 15
        elif request.GET['limit'] is 20:
            limit = 20

    if user is not None:
        try:
            post = post.objects.filter(post_owner_id=user)
        except Post.DoesNotExist:
            post = Post.objects.all()

    if 'post_type' in request.GET:
        if request.GET['post_type'] == 'academic' or request.GET['post_type'] == 'office':
            post = post.filter(post_type=request.GET['post_type'])
        else:
            post = Post.objects.all()

    if 'post_tags' in request.GET:
        if request.GET['post_tags']:
            post = Post.objects.filter(post_tags__name__in=request.GET['post_tags'].split())

    if 'post_type' in request.GET:
        initial['post_type'] = request.GET['post_type']

    if 'limit' in request.GET:
        initial['limit'] = request.GET['limit']

    if 'post_tags' in request.GET:
        initial['post_tags'] = request.GET['post_tags']

    if user is not None:
        searchForm = SearchPost(initial=initial, userId=user)
    else:
        searchForm = SearchPost(initial=initial)

    page = int(page)
    pages = math.ceil(post.count() / limit)
    post = post.order_by('-post_posted')
    paginator = Paginator(post, limit)

    try:
        paginator = paginator.page(page)
    except PageNotAnInteger:
        paginator = paginator.page(1)
    except EmptyPage:
        paginator = paginator.page(paginator.num_pages)

    return render(request, 'posts.html', {'page': page, 'pages': pages, 'data': paginator, 'form': searchForm})

def profile(request, user=None):
    initial = {}
    limit = 10
    page = 1
    post = Post
    searchForm = SearchPost
    account = None

    if 'page' in request.GET:
        page = request.GET['page']

    if 'limit' in request.GET:
        if request.GET['limit'] is 15:
            limit = 15
        elif request.GET['limit'] is 20:
            limit = 20

    if user is not None:
        try:
            post = post.objects.filter(post_owner_id=user)
        except Post.DoesNotExist:
            post = Post.objects.all()
    elif 'user' in request.GET:
        post = post.objects.filter(post_owner_id=request.GET['user'])
    elif 'uid' in request.session:
        post = post.objects.filter(post_owner_id=request.session['uid'])

    if 'post_type' in request.GET:
        if request.GET['post_type'] == 'academic' or request.GET['post_type'] == 'office':
            post = post.objects.filter(post_type=request.GET['post_type'])
        else:
            post = Post.objects.all()

    if 'post_tags' in request.GET:
        if request.GET['post_tags']:
            post = Post.objects.filter(post_tags__name__in=request.GET['post_tags'].split())

    if 'post_type' in request.GET:
        initial['post_type'] = request.GET['post_type']

    if 'limit' in request.GET:
        initial['limit'] = request.GET['limit']

    if 'post_tags' in request.GET:
        initial['post_tags'] = request.GET['post_tags']

    if user is not None:
        account = User.objects.get(id=user)
        searchForm = SearchPost(initial=initial, userId=user)
    elif 'user' in request.GET:
        account = User.objects.get(id=request.GET['user'])
        searchForm = SearchPost(initial=initial, userId=request.GET['user'])
    elif 'uid' in request.session:
        account = User.objects.get(id=request.session['uid'])
        searchForm = SearchPost(initial=initial, userId=request.session['uid'])

    page = int(page)
    pages = math.ceil(post.count() / limit)
    post = post.order_by("-post_posted")
    paginator = Paginator(post, limit)

    try:
        paginator = paginator.page(page)
    except PageNotAnInteger:
        paginator = paginator.page(1)
    except EmptyPage:
        paginator = paginator.page(paginator.num_pages)

    return render(request, 'profile.html', {'page': page, 'pages': pages, 'data': paginator, 'form': searchForm, 'account': account})

def logout(request):
    request.session.flush()
    return HttpResponseRedirect("/")

def post(request):
    form = SearchPost()
    postForm = PostItem()

    if 'uid' not in request.session:
        return HttpResponseRedirect('/')
    else:
        if request.method == 'POST':
            postForm = PostItem(data=request.POST, files=request.FILES)

            if postForm.is_valid():
                post = postForm.save(commit=False)
                post.post_owner = User.objects.get(id=request.session['uid'])
                post.save()
                postForm.save_m2m()

                return profile(request)
            else:
                return render(request, 'post.html',
                              {'form': form, 'post': postForm, 'error': postForm.errors})
        else:
            return render(request, 'post.html', {'form': form, 'post': postForm})


def login(request):
    form = SearchPost()
    loginForm = UserLogin()

    if 'uid' in request.session:
        return HttpResponseRedirect('/profile/')
    else:
        if request.method == 'POST':
            loginForm = UserLogin(data=request.POST, files=request.FILES)

            if loginForm.is_valid():
                try:
                    user = User.objects.get(user_email=loginForm.cleaned_data.get('user_email'))

                    try:
                        user = User.objects.get(user_email=loginForm.cleaned_data.get('user_email'), user_password=loginForm.cleaned_data.get('user_password'))

                        request.session.flush()
                        request.session['uid'] = user.id

                        return HttpResponseRedirect('/profile/')
                    except User.DoesNotExist:
                        return render(request, 'login.html', {'form': form, 'login': loginForm, 'error': 'Password is incorrect'})

                except User.DoesNotExist:
                    return render(request, 'login.html', {'form': form, 'login': loginForm, 'error': 'Account does not exist'})
            else:
                print(loginForm.errors)
                return render(request, 'login.html',
                              {'form': form, 'login': loginForm, 'error': loginForm.errors})
        else:
            return render(request, 'login.html', {'form': form, 'login': loginForm})

def register(request):
    form = SearchPost()
    regisForm = UserRegister()

    if 'uid' in request.session:
        return HttpResponseRedirect('/profile/')
    else:
        if request.method == "POST":
            regisForm = UserRegister(data=request.POST)

            if regisForm.is_valid():
                user = User.objects.filter(user_email=regisForm.cleaned_data.get("user_email"))

                if user.count() <= 0:
                    regisForm.save()

                    return HttpResponseRedirect("/login/")
                else:
                    return render(request, 'register.html',
                                  {'form': form, 'register': regisForm, 'error': 'Email is already used'})
            else:
                return render(request, 'register.html',
                              {'form': form, 'register': regisForm, 'error': 'An error occurred while registering'})
        else:
            return render(request, 'register.html', {'form': form, 'register': regisForm})


def viewItem(request):
    if 'uid' in request.session and 'item' in request.GET:
        post = Post.objects.get(id=request.GET['item'])
        offer = None

        if 'view' in request.GET:
            if request.GET['view'] == 'items':
                offer = ItemOffer.objects.filter(itemO_offer__offer_post=post)

                if offer.count() == 0:
                    offer = None

                return render(request, 'viewItem.html',
                              {'post': post, 'form': SearchPost(), 'item': request.GET['item'], 'displayItem': offer})
            else:
                offer = MoneyOffer.objects.filter(moneyO_offer__offer_post=post)

                if offer.count() == 0:
                    offer = None

                return render(request, 'viewItem.html',
                              {'post': post, 'form': SearchPost(), 'item': request.GET['item'], 'displayMoney': offer})

        try:
            offerU = Offer.objects.get(offer_post_id=request.GET['item'], offer_user_id=request.session['uid'])

            try:
                offer = ItemOffer.objects.get(itemO_offer=offerU)
            except ItemOffer.DoesNotExist:
                try:
                    offer = MoneyOffer.objects.get(moneyO_offer=offerU)
                except MoneyOffer.DoesNotExist:
                    offer = None
        except Offer.DoesNotExist:
            offer = None

        if offer == None:
            if 'itemOffer' in request.POST:
                return render(request, 'viewItem.html', {'post': post, 'form': SearchPost(), 'offer': OfferItem(user=request.session['uid']), 'item': request.GET['item']})
            elif 'moneyOffer' in request.POST:

mp3/post/templates/login.html
{% load static %}
{% load filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if 'user' in request.session %}
            {{ request.session.user|getUserName }}
        {% else %}
            New Beginnings - Login
        {% endif %}
    </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div id="nav">
        <form action="/" method="GET" id="frmSearch">
            <p style="text-transform: uppercase;"><a href="/">New Beginnings</a></p>
            {{ form.as_p }}
            <input type="submit" value="Search" id="search">

            <ul>
                <li>
                    Account
                    <ul>
                        {% if request.session|getUser == None %}
                            <li><a href="/login/">Log In</a></li>
                            <li><a href="/register/">Register</a></li>
                        {% else %}
                            <li><a href="/profile/">Profile</a></li>
                            <li><a href="/messages/">Messages</a></li>
                            <li><a href="/post/">Post An Item</a></li>
                            <li><a href="/logou/">Log Out</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </form>
    </div>

    <div id="form">
        <form action="/login/" method="POST">
            <h1>Log In</h1>
            <hr>
            {% csrf_token %}
            {{ login.as_p }}
            <div class="center">
                <input type="submit" value="Log In" id="btn" style="padding: 10px; width: 150px;">
            </div>
            {% if error %}
                <div style="background-color: #b85e50; padding: 7px; margin-top: 10px; border-radius: 3px;"><b>Error:</b> {{ error }}</div>
            {% endif %}
        </form>
    </div>
</body>

</html>

mp3/post/templates/post.html
{% load static %}
{% load filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if 'user' in request.session %}
            {{ request.session.user|getUserName }}
        {% else %}
            New Beginnings - View Posts
        {% endif %}
    </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div id="nav">
        <form action="/" method="GET" id="frmSearch">
            <p style="text-transform: uppercase;"><a href="/">New Beginnings</a></p>
            {{ form.as_p }}
            <input type="submit" value="Search" id="search">

            <ul>
                <li>
                    Account
                    <ul>
                        {% if request.session|getUser == None %}
                            <li><a href="/login/">Log In</a></li>
                            <li><a href="/register/">Register</a></li>
                        {% else %}
                            <li><a href="/profile/">Profile</a></li>
                            <li><a href="/messages/">Messages</a></li>
                            <li><a href="/post/">Post An Item</a></li>
                            <li><a href="/logout/">Log Out</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </form>
    </div>

    <div id="form">
        <form action="/post/" method="POST">
            <h1>Post Item</h1>
            <hr>
            {% csrf_token %}
            {{ post.as_p }}
            <div class="center">
                <input type="submit" value="Post Item" id="btn" style="padding: 10px; width: 150px;">
            </div>
            {% if error %}
                <div style="background-color: #b85e50; padding: 7px; margin-top: 10px; border-radius: 3px;"><b>Error:</b> {{ error }}</div>
            {% endif %}
        </form>
    </div>
</body>

</html>

mp3/post/templates/posts.html
{% load static %}
{% load filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if 'user' in request.session %}
            {{ request.session.user|getUserName }}
        {% else %}
            New Beginnings - View Posts
        {% endif %}
    </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div id="nav">
        <form action="/" method="GET" id="frmSearch">
            <p style="text-transform: uppercase;"><a href="/">New Beginnings</a></p>
            {{ form.as_p }}
            <input type="submit" value="Search" id="search">

            <ul>
                <li>
                    Account
                    <ul>
                        {% if request.session|getUser == None %}
                            <li><a href="/login/">Log In</a></li>
                            <li><a href="/register/">Register</a></li>
                        {% else %}
                            <li><a href="/profile/">Profile</a></li>
                            <li><a href="/messages/">Messages</a></li>
                            <li><a href="/post/">Post An Item</a></li>
                            <li><a href="/logout/">Log Out</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </form>
    </div>

    <div id="posts">
        {% if pages != '0' or pages != 0 %}
            <div style="margin-top: 25px; text-align: center;" id="postControls">
                {% if page > 1 %}
                    <a href="#" id="prevPage" data-page="{{ page|add:-1 }}">Previous</a>
                {% endif %}
                    Page {{ page }} of {{ pages }}
                {% if page < pages %}
                    <a href="#" id="nextPage" data-page="{{ page|add:1 }}">Next</a>
                {% endif %}
            </div>

            {% for d in data %}
                <div class="post">
                    <a href="{{ d.post_pic.url }}"> <img src="{{ d.post_pic.url }}" alt="{{ d.post_name }}"></a>
                    <div class="postDetails">
                        <p><b>Name: </b> {{ d.post_name }}</p>
                        <p><b>Description: </b> {{ d.post_description }}</p>
                        <p><b>Owner: </b> <a href="/profile/?user={{ d.post_owner.id }}">{{ d.post_owner.user_name }}</a></p>
                        <p><b>Type: </b> <span onclick="searchType('{{ d.post_type }}')">{% if d.post_type == 'academic' %} Academic {% else %} Office {% endif %}</span></p>
                        {% if d.post_type == 'academic' %}
                            <p><b>Course: </b> {{ d.post_course }}</p>
                        {% endif %}
                        <p><b>Tags: </b>
                            {% for tag in d.post_tags.names %}
                                <span class="tag" onclick="searchTag(this)">{{ tag }}</span>
                            {% endfor %}
                        </p>
                        {% if request.session|getUser is not None %}
                            <p><a href="/viewItem/?item={{ d.id }}">View Item Details</a></p>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div style="text-transform: uppercase; text-align: center; margin-top: 25px;"><h1>There are no posts!</h1></div>
        {% endif %}
    </div>
</body>
<script src="{% static 'jquery-3.2.1.min.js' %}"></script>
<script>
    function searchTag(obj){
        $("#id_post_tags").val(obj.innerHTML);
        $("#frmSearch").submit()
    }

    function searchType(type){
        $("#id_post_type").val(type);
        $("#frmSearch").submit()
    }
</script>
</html>

mp3/post/templates/profile.html
{% load static %}
{% load filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if 'user' in request.session %}
            {{ request.session.user|getUserName }}
        {% else %}
            New Beginnings - View Profile
        {% endif %}
    </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div id="nav">
        <form action="/profile/" method="GET" id="frmSearch">
            <p style="text-transform: uppercase;"><a href="/">New Beginnings</a></p>
            {{ form.as_p }}
            <input type="submit" value="Search" id="search">

            <ul>
                <li>
                    Account
                    <ul>
                        {% if request.session|getUser == None %}
                            <li><a href="/login/">Log In</a></li>
                            <li><a href="/register/">Register</a></li>
                        {% else %}
                            <li><a href="/profile/">Profile</a></li>
                            <li><a href="/messages/">Messages</a></li>
                            <li><a href="/post/">Post An Item</a></li>
                            <li><a href="/logout/">Log Out</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </form>
    </div>

    <div id="user">
        <div id="info">
            <div id="img"><img src="{{ account.user_pic.url }}" alt=""></div>
            <div id="details">
                <div id="name"><h1>{{ account.user_name }}</h1></div>
                <div id="email"><b>Email:</b> {{ account.user_email }}</div>
                <div id="type"><b>Type:</b> {% if account.user_type == 'student' %} Student {% else %} Professor {% endif %}</div>
            </div>
        </div>
    </div>

    <hr>
    <div id="posts">
        {% if pages != 0 or pages != '0' %}
            <div style="margin-top: 25px; text-align: center;" id="postControls">
                {% if page > 1 %}
                    <a href="#" id="prevPage" data-page="{{ page|add:-1 }}">Previous</a>
                {% endif %}
                    Page {{ page }} of {{ pages }}
                {% if page < pages %}
                    <a href="#" id="nextPage" data-page="{{ page|add:1 }}">Next</a>
                {% endif %}
            </div>

            {% for d in data %}
                <div class="post">
                    <a href="{{ d.post_pic.url }}"> <img src="{{ d.post_pic.url }}" alt="{{ d.post_name }}"></a>
                    <div class="postDetails">
                        <p><b>Name: </b> {{ d.post_name }}</p>
                        <p><b>Description: </b> {{ d.post_description }}</p>
                        <p><b>Owner: </b> <a href="/profile/?user={{ d.post_owner.id }}">{{ d.post_owner.user_name }}</a></p>
                        <p><b>Type: </b> <span onclick="searchType('{{ d.post_type }}')">{% if d.post_type == 'academic' %} Academic {% else %} Office {% endif %}</span></p>
                        {% if d.post_type == 'academic' %}
                            <p><b>Course: </b> {{ d.post_course }}</p>
                        {% endif %}
                        <p><b>Tags: </b>
                            {% for tag in d.post_tags.names %}
                                <span class="tag" onclick="searchTag(this)">{{ tag }}</span>
                            {% endfor %}
                        </p>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div style="text-transform: uppercase; text-align: center; margin-top: 25px;"><h1>There are no posts!</h1></div>
        {% endif %}
    </div>
</body>
<script src="{% static 'jquery-3.2.1.min.js' %}"></script>
<script>
    function searchTag(obj){
        $("#id_post_tags").val(obj.innerHTML);
        $("#frmSearch").submit()
    }

    function searchType(type){
        $("#id_post_type").value = type;
        $("#frmSearch").submit()
    }
</script>
</html>

mp3/post/templates/register.html
{% load static %}
{% load filter %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% if 'user' in request.session %}
            {{ request.session.user|getUserName }}
        {% else %}
            New Beginnings - Register
        {% endif %}
    </title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    <div id="nav">
        <form action="/" method="GET" id="frmSearch">
            <p style="text-transform: uppercase;"><a href="/">New Beginnings</a></p>
            {{ form.as_p }}
            <input type="submit" value="Search" id="search">

            <ul>
                <li>
                    Account
                    <ul>
                        {% if request.session|getUser == None %}
                            <li><a href="/login/">Log In</a></li>
                            <li><a href="/register/">Register</a></li>
                        {% else %}
                            <li><a href="/profile/">Profile</a></li>
                            <li><a href="/messages/">Messages</a></li>
                            <li><a href="/post/">Post An Item</a></li>
                            <li><a href="/logout/">Log Out</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
        </form>
    </div>

    <div id="form">
        <form action="/register/" method="POST">
            <h1>Register</h1>
            <hr>
            {% csrf_token %}
            {{ register.as_p }}
            <div class="center">
                <input type="submit" value="Register" id="btn" style="padding: 10px; width: 150px;">
            </div>
            {% if error %}
                <div style="background-color: #b85e50; padding: 7px; margin-top: 10px; border-radius: 3px;"><b>Error:</b> {{ error }}</div>
            {% endif %}
        </form>
    </div>
</body>

</html>